dataset_root: /PATH/TO/DATASET/ROOT  # e.g. set this to the unzipped directory of all datasets

datasets:
    pusht: ${env_vars.dataset_root}/pusht_dataset
    sim_kitchen: ${env_vars.dataset_root}/sim_kitchen_dataset
    libero: ${env_vars.dataset_root}/libero_dataset
    block_push: ${env_vars.dataset_root}/block_push_dataset
    your_trajectory_dataset: YOUR_DATASET_PATH